import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PO_GLOB = ROOT / "translations"

# Key messages we will normalize across locales
KEYS = [
    "You do not have permission to access the Admin area.",
    "Translation not found",
    "Translation updated",
    "FX rate not found",
    "FX rate updated",
    "Course created successfully",
    "Error: %(error)s",
    "Course not found",
    "Course updated successfully",
    "Course deleted",
    "Price created",
    "Price not found",
    "Price updated",
    "Price deleted",
    "Evaluation not found",
    # UI strings used in templates (homepage, list, footer)
    "Welcome to TEEtimeVN",
    "Explore Vietnam's top golf courses and book tee times in your language.",
    "Top-Rated Golf Courses",
    "View All Courses",
    "Course List",
    "Golf Courses",
    "Location / City",
    "Select Discount",
    "Select Rating",
    "Filter Courses",
    "Previous",
    "Page",
    "Next",
    "Premium Services",
    "Enjoy curated services for a seamless golf experience in Vietnam.",
    "Tee Time Booking",
    "Private Transfers",
    "Club & Caddy",
    "Lessons & Coaching",
    "Rating",
    "Explore Courses",
    "Contact",
    "Follow us",
    "Get the latest tee time deals and course news.",
    "Mon–Sun",
    "All rights reserved",
    "Privacy",
    "Terms",
    "Language",
]

TRANSLATIONS = {
    "en": {k: k for k in KEYS},
    "vi": {
        "You do not have permission to access the Admin area.": "Bạn không có quyền truy cập khu vực Quản trị.",
        "Translation not found": "Không tìm thấy bản dịch",
        "Translation updated": "Đã cập nhật bản dịch",
        "FX rate not found": "Không tìm thấy tỷ giá",
        "FX rate updated": "Đã cập nhật tỷ giá",
        "Course created successfully": "Tạo sân thành công",
        "Error: %(error)s": "Lỗi: %(error)s",
        "Course not found": "Không tìm thấy sân",
        "Course updated successfully": "Cập nhật sân thành công",
        "Course deleted": "Đã xóa sân",
        "Price created": "Tạo giá thành công",
        "Price not found": "Không tìm thấy giá",
        "Price updated": "Cập nhật giá thành công",
        "Price deleted": "Đã xóa giá",
        "Evaluation not found": "Không tìm thấy đánh giá",
        "Welcome to TEEtimeVN": "Chào mừng đến với TEEtimeVN",
        "Explore Vietnam's top golf courses and book tee times in your language.": "Khám phá các sân golf hàng đầu Việt Nam và đặt giờ chơi bằng ngôn ngữ của bạn.",
        "Top-Rated Golf Courses": "Sân golf được đánh giá cao",
        "View All Courses": "Xem tất cả sân",
        "Course List": "Danh sách sân",
        "Golf Courses": "Sân golf",
        "Location / City": "Vị trí / Thành phố",
        "Select Discount": "Chọn mức giảm giá",
        "Select Rating": "Chọn điểm đánh giá",
        "Filter Courses": "Lọc sân golf",
        "Previous": "Trước",
        "Page": "Trang",
        "Next": "Sau",
        "Premium Services": "Dịch vụ cao cấp",
        "Enjoy curated services for a seamless golf experience in Vietnam.": "Tận hưởng các dịch vụ chọn lọc cho trải nghiệm golf trọn vẹn tại Việt Nam.",
        "Tee Time Booking": "Đặt giờ chơi",
        "Private Transfers": "Xe đưa đón riêng",
        "Club & Caddy": "Gậy & Caddy",
        "Lessons & Coaching": "Khóa học & Huấn luyện",
        "Rating": "Điểm",
        "Explore Courses": "Khám phá sân",
        "Contact": "Liên hệ",
        "Follow us": "Theo dõi chúng tôi",
        "Get the latest tee time deals and course news.": "Nhận ưu đãi tee time và tin tức sân mới nhất.",
        "Mon–Sun": "Thứ 2–Chủ nhật",
        "All rights reserved": "Bảo lưu mọi quyền",
        "Privacy": "Chính sách bảo mật",
        "Terms": "Điều khoản",
        "Language": "Ngôn ngữ",
    },
    "ja": {
        "You do not have permission to access the Admin area.": "管理エリアへのアクセス権限がありません。",
        "Translation not found": "翻訳が見つかりません",
        "Translation updated": "翻訳を更新しました",
        "FX rate not found": "為替レートが見つかりません",
        "FX rate updated": "為替レートを更新しました",
        "Course created successfully": "コースを作成しました",
        "Error: %(error)s": "エラー: %(error)s",
        "Course not found": "コースが見つかりません",
        "Course updated successfully": "コースを更新しました",
        "Course deleted": "コースを削除しました",
        "Price created": "料金を作成しました",
        "Price not found": "料金が見つかりません",
        "Price updated": "料金を更新しました",
        "Price deleted": "料金を削除しました",
        "Evaluation not found": "評価が見つかりません",
        "Welcome to TEEtimeVN": "TEEtimeVN へようこそ",
        "Explore Vietnam's top golf courses and book tee times in your language.": "ベトナムの人気ゴルフ場を探し、あなたの言語でティータイムを予約しましょう。",
        "Top-Rated Golf Courses": "高評価のゴルフコース",
        "View All Courses": "すべてのコースを見る",
        "Course List": "コース一覧",
        "Golf Courses": "ゴルフコース",
        "Location / City": "所在地 / 都市",
        "Select Discount": "割引を選択",
        "Select Rating": "評価を選択",
        "Filter Courses": "コースを絞り込む",
        "Previous": "前へ",
        "Page": "ページ",
        "Next": "次へ",
        "Premium Services": "プレミアムサービス",
        "Enjoy curated services for a seamless golf experience in Vietnam.": "ベトナムで快適なゴルフ体験のための厳選サービスをご提供します。",
        "Tee Time Booking": "ティータイム予約",
        "Private Transfers": "専用送迎",
        "Club & Caddy": "クラブ＆キャディ",
        "Lessons & Coaching": "レッスン＆コーチング",
        "Rating": "評価",
        "Explore Courses": "コースを探す",
        "Contact": "お問い合わせ",
        "Follow us": "フォローする",
        "Get the latest tee time deals and course news.": "最新のティータイム特典とコース情報をお届けします。",
        "Mon–Sun": "月–日",
        "All rights reserved": "無断転載を禁じます",
        "Privacy": "プライバシー",
        "Terms": "利用規約",
        "Language": "言語",
    },
    "ko": {
        "You do not have permission to access the Admin area.": "관리자 영역에 접근할 권한이 없습니다.",
        "Translation not found": "번역을 찾을 수 없습니다",
        "Translation updated": "번역이 업데이트되었습니다",
        "FX rate not found": "환율 정보를 찾을 수 없습니다",
        "FX rate updated": "환율 정보가 업데이트되었습니다",
        "Course created successfully": "코스가 생성되었습니다",
        "Error: %(error)s": "오류: %(error)s",
        "Course not found": "코스를 찾을 수 없습니다",
        "Course updated successfully": "코스가 업데이트되었습니다",
        "Course deleted": "코스가 삭제되었습니다",
        "Price created": "요금이 생성되었습니다",
        "Price not found": "요금을 찾을 수 없습니다",
        "Price updated": "요금이 업데이트되었습니다",
        "Price deleted": "요금이 삭제되었습니다",
        "Evaluation not found": "평가를 찾을 수 없습니다",
        "Welcome to TEEtimeVN": "TEEtimeVN에 오신 것을 환영합니다",
        "Explore Vietnam's top golf courses and book tee times in your language.": "베트남 최고의 골프장을 찾아 당신의 언어로 티타임을 예약하세요.",
        "Top-Rated Golf Courses": "평점이 높은 골프장",
        "View All Courses": "모든 코스 보기",
        "Course List": "코스 목록",
        "Golf Courses": "골프 코스",
        "Location / City": "지역 / 도시",
        "Select Discount": "할인 선택",
        "Select Rating": "평점 선택",
        "Filter Courses": "코스 필터",
        "Previous": "이전",
        "Page": "페이지",
        "Next": "다음",
        "Premium Services": "프리미엄 서비스",
        "Enjoy curated services for a seamless golf experience in Vietnam.": "베트남에서 더욱 편안한 골프 경험을 위한 맞춤형 서비스를 제공합니다.",
        "Tee Time Booking": "티타임 예약",
        "Private Transfers": "전용 차량 이동",
        "Club & Caddy": "클럽 & 캐디",
        "Lessons & Coaching": "레슨 & 코칭",
        "Rating": "평점",
        "Explore Courses": "코스 둘러보기",
        "Contact": "문의",
        "Follow us": "팔로우하기",
        "Get the latest tee time deals and course news.": "최신 티타임 혜택과 코스 소식을 받아보세요.",
        "Mon–Sun": "월–일",
        "All rights reserved": "판권 소유",
        "Privacy": "개인정보처리방침",
        "Terms": "이용약관",
        "Language": "언어",
    },
    "zh_Hans_CN": {
        "You do not have permission to access the Admin area.": "您没有权限访问管理区域。",
        "Translation not found": "未找到翻译",
        "Translation updated": "翻译已更新",
        "FX rate not found": "未找到汇率",
        "FX rate updated": "汇率已更新",
        "Course created successfully": "球场创建成功",
        "Error: %(error)s": "错误：%(error)s",
        "Course not found": "未找到球场",
        "Course updated successfully": "球场更新成功",
        "Course deleted": "已删除球场",
        "Price created": "价格已创建",
        "Price not found": "未找到价格",
        "Price updated": "价格已更新",
        "Price deleted": "价格已删除",
        "Evaluation not found": "未找到评价",
        "Welcome to TEEtimeVN": "欢迎来到 TEEtimeVN",
        "Explore Vietnam's top golf courses and book tee times in your language.": "探索越南顶级高尔夫球场，并使用你的语言预订开球时间。",
        "Top-Rated Golf Courses": "高评分球场",
        "View All Courses": "查看全部球场",
        "Course List": "球场列表",
        "Golf Courses": "高尔夫球场",
        "Location / City": "位置 / 城市",
        "Select Discount": "选择折扣",
        "Select Rating": "选择评分",
        "Filter Courses": "筛选球场",
        "Previous": "上一页",
        "Page": "页",
        "Next": "下一页",
        "Premium Services": "精选服务",
        "Enjoy curated services for a seamless golf experience in Vietnam.": "在越南享受精心打造的无缝高尔夫服务体验。",
        "Tee Time Booking": "开球时间预订",
        "Private Transfers": "专车接送",
        "Club & Caddy": "球杆租赁与球童",
        "Lessons & Coaching": "课程与教学",
        "Rating": "评分",
        "Explore Courses": "探索球场",
        "Contact": "联系",
        "Follow us": "关注我们",
        "Get the latest tee time deals and course news.": "获取最新的开球优惠与球场资讯。",
        "Mon–Sun": "周一–周日",
        "All rights reserved": "版权所有",
        "Privacy": "隐私政策",
        "Terms": "使用条款",
        "Language": "语言",
    },
    "zh_Hant_TW": {
        "You do not have permission to access the Admin area.": "您沒有權限存取管理區域。",
        "Translation not found": "找不到翻譯",
        "Translation updated": "已更新翻譯",
        "FX rate not found": "找不到匯率",
        "FX rate updated": "已更新匯率",
        "Course created successfully": "球場建立成功",
        "Error: %(error)s": "錯誤：%(error)s",
        "Course not found": "找不到球場",
        "Course updated successfully": "球場更新成功",
        "Course deleted": "已刪除球場",
        "Price created": "已建立價格",
        "Price not found": "找不到價格",
        "Price updated": "價格已更新",
        "Price deleted": "已刪除價格",
        "Evaluation not found": "找不到評價",
        "Welcome to TEEtimeVN": "歡迎來到 TEEtimeVN",
        "Explore Vietnam's top golf courses and book tee times in your language.": "探索越南頂級高爾夫球場，並以你的語言預訂開球時間。",
        "Top-Rated Golf Courses": "高評分球場",
        "View All Courses": "查看全部球場",
        "Course List": "球場列表",
        "Golf Courses": "高爾夫球場",
        "Location / City": "位置 / 城市",
        "Select Discount": "選擇折扣",
        "Select Rating": "選擇評分",
        "Filter Courses": "篩選球場",
        "Previous": "上一頁",
        "Page": "頁",
        "Next": "下一頁",
        "Premium Services": "精選服務",
        "Enjoy curated services for a seamless golf experience in Vietnam.": "在越南享受精心打造、無縫的高爾夫服務體驗。",
        "Tee Time Booking": "開球時間預訂",
        "Private Transfers": "專車接送",
        "Club & Caddy": "球桿租借與桿弟",
        "Lessons & Coaching": "課程與教學",
        "Rating": "評分",
        "Explore Courses": "探索球場",
        "Contact": "聯絡我們",
        "Follow us": "追蹤我們",
        "Get the latest tee time deals and course news.": "接收最新的開球優惠與球場資訊。",
        "Mon–Sun": "週一–週日",
        "All rights reserved": "版權所有",
        "Privacy": "隱私權政策",
        "Terms": "使用條款",
        "Language": "語言",
    },
}


def normalize_file(po_path: Path) -> int:
    text = po_path.read_text(encoding="utf-8")

    # Remove fuzzy markers
    text = re.sub(r"^#,\s*fuzzy\s*$", "", text, flags=re.MULTILINE)

    # Choose language map
    lang = po_path.parts[-3]
    trans = TRANSLATIONS.get(lang, {})

    # Replace msgstr for known keys
    def repl_for(msgid: str, msgstr: str, s: str) -> str:
        # Escape quotes
        eid = re.escape(msgid)
        pattern = rf"(?m)^msgid\s+\"{eid}\"\s*\nmsgstr\s+\".*?\""
        replacement = f'msgid "{msgid}"\nmsgstr "{msgstr}"'
        return re.sub(pattern, replacement, s)

    before = text
    for k, v in trans.items():
        text = repl_for(k, v, text)

    changed = 0 if text == before else 1
    po_path.write_text(text, encoding="utf-8")
    return changed


def main():
    changed_total = 0
    count_files = 0
    for po in PO_GLOB.rglob("messages.po"):
        count_files += 1
        changed_total += normalize_file(po)
    print(f"Processed {count_files} files. Updated: {changed_total}")


if __name__ == "__main__":
    main()

